### ISSUE TITLE
Budget term: confusion with the budget term 

### ISSUE THREAD

**Issue by CristinaEche** [MinaFoundation/PGT_govbotOCVFrontend#7]
Illya

During the On-chain voting phase, some users were confused by the term 'Budget,' thinking it referred to the amount of MINA they would transfer by voting for the proposal. Could you please change the label to something like 'Proposal Required Budget for Execution' or a similar term to clarify?

<img width="222" alt="image" src="https://github.com/user-attachments/assets/3a31c39c-cfc2-446b-8dd4-82a71a3dc1ae">

**Comment by iluxonchik** [comment]
'Proposal Required Budget for Execution' sounded too long/complex, so I put "Requested Budget". Is that okay?

**Comment by CristinaEche** [comment]
is ok , tks!
